### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sagiraju1** [sunilsankar/pega-pe#7]
i am getting below error  below .when i am running sh install.sh
The repository 'http://apt.postgresql.org/pub/repos/apt -pgdg Release' does not have a Release file.

**Comment by sunilsankar** [comment]
Can you run the below command and paste the output
```
apt update 
```

**Comment by Sagiraju1** [comment]
no luck getting same error as below.

root@5e260e2fdca1:/# apt update       
Hit:1 http://deb.debian.org/debian bullseye InRelease
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Ign:4 http://apt.postgresql.org/pub/repos/apt -pgdg InRelease
Err:5 http://apt.postgresql.org/pub/repos/apt -pgdg Release
  404  Not Found [IP: 72.32.157.246 80]
Reading package lists... Done
E: The repository 'http://apt.postgresql.org/pub/repos/apt -pgdg Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@5e260e2fdca1:/#

**Comment by Sagiraju1** [comment]
> Can you run the below command and paste the output
> 
> ```
> apt update 
> ```

no luck getting same error as below.

root@5e260e2fdca1:/# apt update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Ign:4 http://apt.postgresql.org/pub/repos/apt -pgdg InRelease
Err:5 http://apt.postgresql.org/pub/repos/apt -pgdg Release
404 Not Found [IP: 72.32.157.246 80]
Reading package lists... Done
E: The repository 'http://apt.postgresql.org/pub/repos/apt -pgdg Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@5e260e2fdca1:/#

**Comment by sunilsankar** [comment]
Can you please share this output 
```
cat /etc/os-release
```
```
uname -m
```

**Comment by Sagiraju1** [comment]
> Can you please share this output
> 
> ```
> cat /etc/os-release
> ```
> 
> ```
> uname -m
> ```

root@5e260e2fdca1:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@5e260e2fdca1:/# uname -m
x86_64
root@5e260e2fdca1:/#

**Comment by sunilsankar** [comment]
I think the latest release of debian has removed this command lsb_release hence the issue . Can you pls try this
```
echo > /etc/apt/sources.list.d/pgdg.list
apt clean all && apt update && apt install -y lsb-release
```
After this please run the install.sh script.

I will include this package in the script once you confirm you get past this error 😃

**Comment by Sagiraju1** [comment]
it worked fine. Thanks for the fast response. Appreciated it. Great work.
