### ISSUE TITLE
 pega-pe - error - ubuntu - aws instance

### ISSUE THREAD

**Issue by msingh1304** [sunilsankar/pega-pe#8]
@sunilsankar - I am getting this error message, getting this in the logs. It is not working for me.

"2023-06-12 06:06:24,127 [ PegaRULES-Batch-10] [ STANDARD] [ ] [ PegaRULES:8] (PortNumber.PESetup_Work.Action) INFO ACR003NP012QXCMANIZ4RDISHAN8D5PA - PETomcatHTTPPort = null." 

I also tried changing the port to 80 and 8443 by going server.xml file but it didn't work. Could you please help?

**Comment by sunilsankar** [comment]
Is your application working since the message is only info

**Comment by msingh1304** [comment]
> Is your application working since the message is only info

It is not working when I am trying to access the url.

**Comment by sunilsankar** [comment]
Did you follow all the steps according to the document and also the tomcat version

**Comment by msingh1304** [comment]
> Did you follow all the steps according to the document and also the tomcat version

Yes, I followed all the steps that was mentioned in the git hub repo.

**Comment by sunilsankar** [comment]
Pega personal edition which one did you use

**Comment by msingh1304** [comment]
> Pega personal edition which one did you use

I used the same one mentioned here that is 8.7

**Comment by sunilsankar** [comment]
Pls share your os version and also the complete zip name of pega personal edition

**Comment by msingh1304** [comment]
> Pls share your os version and also the complete zip name of pega personal edition

I used this link to download personal edition: https://harshatrainings.com/downloads/

"[Click here to Download Pega Software 8.7 V](https://drive.google.com/file/d/12W6WNWOvKInqrIiIRMm_b8erCIGJbbI4/view)"

Here is the OS version details

PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

And here is the tomcat version : apache-tomcat-8.5.14

**Comment by sunilsankar** [comment]
Can you also paste the output of this command 
```
uname -m
```

**Comment by msingh1304** [comment]
> Can you also paste the output of this command
> 
> ```
> uname -m
> ```

x86_64

**Comment by msingh1304** [comment]
@sunilsankar 

Did you find anything?

**Comment by sunilsankar** [comment]
I will test and let you know since I used debian I will test it on ubuntu

**Comment by msingh1304** [comment]
Thanks for confirming!

**Comment by sunilsankar** [comment]
@msingh1304 pls try tomcat on 8080 not 8443. if you have made changes to server.xml. Please replace it with this file
https://github.com/sunilsankar/pega-pe/blob/master/conf/server.xml

and restart tomcat

**Comment by sunilsankar** [comment]
Can you pls paste the output of 
```
ps -ef|grep java
netstat -aunltp|grep java
```

**Comment by msingh1304** [comment]
It was earlier 8080 only, I changed it only from troubleshooting
perspective, it was not working before also. I have now changed it back to
8080 , used the server.xml file you provided. And also pasted the output of
the command you suggested.
Thanks & Regards,
Manish Singh(987-020-7179)

**Comment by msingh1304** [comment]
ps -ef|grep java

root        2976       1  9 Jun14 ?        02:04:07 /usr/bin/java -Djava.util.logging.config.file=/opt/apache-tomcat-8.5.14/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms4096m -Xmx4096m -DNodeType=Stream,BackgroundProcessing,WebUser,Search -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -classpath /opt/apache-tomcat-8.5.14/bin/bootstrap.jar:/opt/apache-tomcat-8.5.14/bin/tomcat-juli.jar -Dcatalina.base=/opt/apache-tomcat-8.5.14 -Dcatalina.home=/opt/apache-tomcat-8.5.14 -Djava.io.tmpdir=/opt/apache-tomcat-8.5.14/temp org.apache.catalina.startup.Bootstrap start
root       73225       1 99 05:32 pts/1    00:01:16 /usr/bin/java -Djava.util.logging.config.file=/opt/apache-tomcat-8.5.14/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms4096m -Xmx4096m -DNodeType=Stream,BackgroundProcessing,WebUser,Search -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -classpath /opt/apache-tomcat-8.5.14/bin/bootstrap.jar:/opt/apache-tomcat-8.5.14/bin/tomcat-juli.jar -Dcatalina.base=/opt/apache-tomcat-8.5.14 -Dcatalina.home=/opt/apache-tomcat-8.5.14 -Djava.io.tmpdir=/opt/apache-tomcat-8.5.14/temp org.apache.catalina.startup.Bootstrap start
root       73369   73006  0 05:33 pts/1    00:00:00 grep --color=auto java

**Comment by msingh1304** [comment]
netstat -aunltp|grep java
tcp6       0      0 :::8080                 :::*                    LISTEN      73225/java
tcp6       0      0 162.81.14.336:7003      :::*                    LISTEN      73225/java
tcp6       0      0 :::9009                 :::*                    LISTEN      73939/java
tcp6       0      0 127.0.0.1:44904         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:44854         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:53598         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:44898         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:33444         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:53650         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:53612         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:53662         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:45122         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:44878         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:53582         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:45112         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:53628         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:33438         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:53588         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:53630         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:53568         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:44872         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:53626         127.0.0.1:5432          ESTABLISHED 73225/java
tcp6       0      0 127.0.0.1:44868         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:44840         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:44842         127.0.0.1:5432          ESTABLISHED 73939/java
tcp6       0      0 127.0.0.1:44886         127.0.0.1:5432          ESTABLISHED 73939/java

**Comment by msingh1304** [comment]
@sunilsankar , I pasted the requested output

**Comment by sunilsankar** [comment]
This command also
```
wget http://localhost:8080/prweb/
```

**Comment by msingh1304** [comment]
wget http://localhost:8080/prweb/
--2023-06-15 05:45:47--  http://localhost:8080/prweb/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 307
Location: http://localhost:8080/prweb/app/default/ [following]
--2023-06-15 05:45:47--  http://localhost:8080/prweb/app/default/
Reusing existing connection to localhost:8080.
HTTP request sent, awaiting response... 303
Location: http://localhost:8080/prweb/app/default/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD [following]
Warning: wildcards not supported in HTTP.
--2023-06-15 05:45:47--  http://localhost:8080/prweb/app/default/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD
Reusing existing connection to localhost:8080.
HTTP request sent, awaiting response... 200
Length: 23902 (23K) [text/html]
Saving to: ‘index.html’

index.html                     100%[==================================================>]  23.34K  --.-KB/s    in 0s

**Comment by msingh1304** [comment]
@sunilsankar 

FYI: I tried replacing the localhost with my internal ip, it doesn't work, can we associate static public ip to this set up that listens on port 80, because port 8080 is sometimes blocked at many places.

**Comment by sunilsankar** [comment]
If you are able to download index.html it means pega is working fine. Don't change server.xml file for now .I will give you a script to setup apache so that you can access via 443 .But you will need to wait

**Comment by msingh1304** [comment]
Sure, thanks a lot. And I can also use static public ip for the url, right?


Regards,
Manish Singh

**Comment by msingh1304** [comment]
@sunilsankar 

It is working now on 8080 port but instead of this I would like to run it on 8443 port, I tried changing the port but it didnot work, any idea?

**Comment by sunilsankar** [comment]
@msingh1304 good to hear it is working in 8080 . To make it work in 8443. take this feature branch
https://github.com/sunilsankar/pega-pe/tree/Feature/ssl
And replace the following files under 
```
/opt/apache-tomcat-8.5.14/conf/
```
with these files in the branch
```
catalina.properties
server.xml
example.crt
example.key
```
